name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Executing remote ssh commands using ssh
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}   
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd apps/next-app
            git pull origin main
            npm install
            npm run build
            pm2 stop next-app || true
            pm2 start npm --name "next-app" -- start
            pm2 save
